# Generated by Django 4.1 on 2022-08-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_on",
            new_name="created",
        ),
    ]
